apiVersion: apps/v1
kind: Deployment
metadata:
  name: donations-deployment
  labels:
    app: donations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donations
  template:
    metadata:
      labels:
        app: donations
    spec:
      containers:
        - name: donations
          image: 519161485873.dkr.ecr.eu-west-1.amazonaws.com/apps/donations:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: awsaccesskeyid
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: awssecretaccesskey
                  key: AWS_SECRET_ACCESS_KEY

---
  
apiVersion: v1
kind: Service
metadata:
  name: donations-service
  labels:
    app: donations
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert:  arn:aws:acm:eu-west-1:519161485873:certificate/013e71bf-4c1d-4a09-86e1-b9489f806ec3
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http 
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  ports:
      - port: 80
        name: http
        targetPort: 8081
      - port: 443
        name: https
        targetPort: 8081
  selector:
      app: donations
  type: LoadBalancer
