version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.5
  gcp: circleci/gcp-cli@1.3

jobs:
  build:
    executor: gcp/default
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - gcp-gcr/
      - gcp/initialize
      - run: docker build -t donations .
      - run: 
          name: Tag & Push image to registry
          command: |
            APP_VERSION=$(cat package.json | jq '.version' --raw-output)
            VERSION="${APP_VERSION}.${CIRCLE_BUILD_NUM}"
            IMG_NAME=$DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$VERSION
            echo $IMG_NAME
            docker tag $DOCKER_IMAGE_NAME $IMG_NAME
            docker push $IMG_NAME
            docker tag $DOCKER_IMAGE_NAME $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest
            docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest
            echo $IMG_NAME > image_id.txt
            echo "$IMG_NAME pushed"
workflows:
  version: 2
  build:
    jobs:
      - gcp-gcr/build-and-push-image:
          name: "Build-Push"
          image: donations
          registry-url: eu.gcr.io
          tag: ${CIRCLE_SHA1:0:7}

