version: 2.1

orbs:
  gcr: circleci/gcp-gcr@0.6

workflows:
  version: 2
  build:
    jobs:
      - gcr/build-and-push-image:
          name: build-push
          image: donations
          registry-url: eu.gcr.io
          tag: ${CIRCLE_SHA1:0:7}
      - gcr/add-image-tag:
          name: tag-latest
          image: donations
          registry-url: eu.gcr.io
          source-tag: ${CIRCLE_SHA1:0:7}
          target-tag: latest
          requires: 
            - build-push
