version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.5

workflows:
  version: 2
  build:
    jobs:
      - gcp-gcr/build-and-push-image:
          name: "Build-Push"
          image: donations
          registry-url: eu.gcr.io
          tag: ${CIRCLE_SHA1:0:7}

